spring:
  application:
    name: fileServer
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fileServer?serverTimezone=Asia/Shanghai&userUnicode=true&characterEncoding=utf-8
    username: root
    password: 8636hyh

server:
  port: 8080
  servlet:
    context-path: /fileServer


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

  type-aliases-package: com.yhao.fileserver.entity

logging:
  level:
    root: info
    com.yhao.fileServer: debug
